### ISSUE TITLE
Displaying Video

### ISSUE THREAD

**Issue by DarLohr** [dcas796/YouTubeKit#1]
Awesome piece of code. 
is there a way to use this to search and display video using these codes? I just need to add  ability to search YouTube videos and play those in my app. not the downloading.

**Comment by dcas796** [comment]
Thanks! Unfortunately, it doesn't support searching videos yet. You would have to use YouTube's API to do it.

For the displaying video part, in theory you could extract the video URL and put it in an `AVPlayer`. Note that video and audio tracks are separate so you would also have to set that up.

If there are more issues, please let me know.
