### ISSUE TITLE
Getiing this error can you help

### ISSUE THREAD

**Issue by Muhammad572** [dcas796/YouTubeKit#2]
'Regex' is only available in iOS 16.0 or newer

<img width="1165" alt="Screenshot 2024-03-31 at 4 09 04 PM" src="https://github.com/dcas796/YouTubeKit/assets/55896578/28d8480a-74ad-4693-aa10-d5dcbb08ddb2">

Concurrency is only available in iOS 13.0.0 or newer

**Comment by dcas796** [comment]
Hello, this error is due to `YouTubeKit` not being available in iOS (I haven't yet added iOS as one of the listed versions in `Package.swift`). I will add iOS support in the next commit (only iOS 16 and above).
